name: tests and benchmarks
run-name: Tests and benchmarks 🚀

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  test:
    # Removemos a restrição de "merged == true" porque agora o push direto também dispara
    # E garantimos que ele rode se for um PR fechado OU um push direto
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run Tests with Coverage
        run: flutter test --coverage --coverage-path=coverage/lcov.info

      - name: Fix coverage file paths
        run: |
          sed -i 's|SF:|SF:lib/|g' coverage/lcov.info
          sed -i 's|SF:lib/lib/|SF:lib/|g' coverage/lcov.info
        shell: bash

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage/lcov.info
          fail_ci_if_error: true 
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true