name: tests and benchmarks
run-name: Tests and benchmarks 🚀
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run Tests with Coverage
        run: flutter test --coverage
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage/lcov.info
          fail_ci_if_error: true 
          token: ${{ secrets.CODECOV_TOKEN }}